# Generated by Django 2.1.2 on 2018-10-16 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cn_name', models.CharField(max_length=128)),
                ('en_name', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='models/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPartsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=11)),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Customer')),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('phone_num', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FactoryPartsPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(max_length=11)),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('factory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Factory')),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('oem', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('cn_name', models.CharField(max_length=128)),
                ('en_name', models.CharField(max_length=128)),
                ('img', models.ImageField(upload_to='parts/%Y/%m/%d/')),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('car_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='partsInfo.CarModels')),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VolumeWeightData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('height', models.FloatField(max_length=10)),
                ('length', models.FloatField(max_length=10)),
                ('width', models.FloatField(max_length=10)),
                ('gross_weight', models.FloatField(max_length=10)),
                ('net_weight', models.FloatField(max_length=10)),
                ('description', models.TextField()),
                ('last_change_date', models.DateField()),
                ('last_change_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Parts')),
            ],
        ),
        migrations.AddField(
            model_name='factorypartsprice',
            name='oem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Parts'),
        ),
        migrations.AddField(
            model_name='factory',
            name='parts',
            field=models.ManyToManyField(through='partsInfo.FactoryPartsPrice', to='partsInfo.Parts'),
        ),
        migrations.AddField(
            model_name='customerpartsprice',
            name='oem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Parts'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parts',
            field=models.ManyToManyField(through='partsInfo.CustomerPartsPrice', to='partsInfo.Parts'),
        ),
    ]
