# Generated by Django 2.1.2 on 2018-10-16 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partsInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OemExchange',
            fields=[
                ('ex_oem', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('oem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='partsInfo.Parts')),
            ],
        ),
    ]
