# Generated by Django 2.1.2 on 2018-10-16 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partsInfo', '0002_oemexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodels',
            name='cn_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='carmodels',
            name='img',
            field=models.ImageField(blank=True, upload_to='models/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customerpartsprice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='factory',
            name='phone_num',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='factorypartsprice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='cn_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='parts',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='parts',
            name='en_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='parts',
            name='img',
            field=models.ImageField(blank=True, upload_to='parts/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='gross_weight',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='height',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='length',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='net_weight',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='volumeweightdata',
            name='width',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
